import "./globals.css";
import { inter } from "./ui/font";
import { lusitana } from "./ui/font";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lusitana.className}`}>{children}</body>
    </html>
  );
}
